# Generated by Django 6.0.7 on 2026-07-21 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='topic',
            field=models.ManyToManyField(blank=True, related_name='categories', to='trivia.entry'),
        ),
    ]
