# Generated by Django 6.0.7 on 2026-07-21 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0002_alter_category_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'Entries'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='topic',
            new_name='entries',
        ),
    ]
