# Generated by Django 6.0.7 on 2026-07-23 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0003_alter_category_options_alter_entry_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='description',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='category',
            name='entries',
        ),
        migrations.AddField(
            model_name='entry',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='entries', to='trivia.category'),
        ),
        migrations.DeleteModel(
            name='Fact',
        ),
    ]
