# Generated by Django 6.0.7 on 2026-07-31 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0004_rename_description_entry_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
